// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"perfect-pic-server/internal/config"
	"perfect-pic-server/internal/handler"
	"perfect-pic-server/internal/middleware"
	"perfect-pic-server/internal/pkg/cache"
	"perfect-pic-server/internal/pkg/database"
	"perfect-pic-server/internal/pkg/email"
	"perfect-pic-server/internal/pkg/jwt"
	"perfect-pic-server/internal/pkg/ratelimit"
	"perfect-pic-server/internal/pkg/redis"
	"perfect-pic-server/internal/repository"
	"perfect-pic-server/internal/router"
	"perfect-pic-server/internal/service"
)

// Injectors from wire.go:

func InitializeApplication() (*Application, error) {
	configConfig := config.NewStaticConfig()
	jwtConfig := config.NewJWTConfig(configConfig)
	jwtJWT := jwt.NewJWT(jwtConfig)
	dbConnectionConfig := config.NewDBConnectionConfig(configConfig)
	db, err := database.NewGormDB(dbConnectionConfig)
	if err != nil {
		return nil, err
	}
	userStore := repository.NewUserRepository(db)
	settingStore := repository.NewSettingRepository(db)
	dbConfig := config.NewDBConfig(settingStore)
	redisConfig := config.NewRedisClientConfig(configConfig)
	client := redis.NewRedisClient(redisConfig)
	cacheConfig := config.NewCacheConfig(configConfig)
	store := cache.NewStore(client, cacheConfig)
	mailer := email.NewMailer()
	emailService := service.NewEmailService(dbConfig, mailer, configConfig)
	imageStore := repository.NewImageRepository(db)
	imageService := service.NewImageService(imageStore, dbConfig, configConfig, userStore)
	passkeyStore := repository.NewPasskeyRepository(db)
	passkeyService := service.NewPasskeyService(passkeyStore, dbConfig, store, jwtJWT, userStore)
	userService := service.NewUserService(userStore, dbConfig, store, jwtJWT, emailService, imageService, passkeyService)
	authMiddleware := middleware.NewAuthMiddleware(jwtJWT, userService)
	ratelimitConfig := config.NewRateLimiterConfig(configConfig)
	baseRateLimiter := ratelimit.NewBaseRateLimiter(client, ratelimitConfig)
	tokenBucketLimiter := ratelimit.NewTokenBucketLimiter(baseRateLimiter)
	intervalLimiter := ratelimit.NewIntervalLimiter(baseRateLimiter)
	rateLimitMiddleware := middleware.NewRateLimitMiddleware(dbConfig, tokenBucketLimiter, intervalLimiter)
	bodyLimitMiddleware := middleware.NewBodyLimitMiddleware(dbConfig)
	securityHeadersMiddleware := middleware.NewSecurityHeadersMiddleware(dbConfig)
	systemStore := repository.NewSystemRepository(db)
	initService := service.NewInitService(systemStore, dbConfig)
	authService := service.NewAuthService(dbConfig, jwtJWT, userStore, userService, emailService, initService)
	captchaService := service.NewCaptchaService(dbConfig)
	authHandler := handler.NewAuthHandler(authService, captchaService, passkeyService, initService, dbConfig)
	systemHandler := handler.NewSystemHandler(initService, dbConfig, configConfig, userService, imageStore, userStore)
	settingsService := service.NewSettingsService(settingStore, dbConfig)
	settingsHandler := handler.NewSettingsHandler(settingsService, emailService)
	userHandler := handler.NewUserHandler(userService, imageService, authService, passkeyService)
	imageHandler := handler.NewImageHandler(imageService)
	routerRouter := router.NewRouter(authMiddleware, rateLimitMiddleware, bodyLimitMiddleware, securityHeadersMiddleware, authHandler, systemHandler, settingsHandler, userHandler, imageHandler)
	staticCacheMiddleware := middleware.NewStaticCacheMiddleware(dbConfig)
	application := NewApplication(routerRouter, dbConfig, db, client, configConfig, staticCacheMiddleware)
	return application, nil
}
